In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [3]:
df['학교'].value_counts()

학교
구로고     5
디지털고    3
Name: count, dtype: int64

In [4]:
# 그룹핑 groupby : size,mean,min,max,
# 그룹화 - 통계,평균
# df.groupby('학교').get_group('구로고')
# df.groupby('학교').get_group('디지털고')
df['학교'].unique()
df.groupby('학교').size()['구로고']
df.groupby('학교').size()['디지털고']
df.groupby('학교').size()  # 학교기준으로 그룹핑을 해서 크기, 전체
df.groupby('학교')['키'].mean()  # 학교기준으로 키 평균 
# df.groupby('학교').mean() # 에러남 문자열과 숫자가 같이 있으면 에러
df.groupby('학교')['국어'].mean() # 에러남 숫자로 만 되어있는 자료는 출력
df.groupby('학교')[['국어','영어','수학']].mean() 
df.groupby('학교')[['국어','영어','수학']].max() 
df.groupby('학교')[['국어','영어','수학']].count()

      국어  영어  수학
학교
구로고    5   5   5
디지털고   3   3   3

In [5]:
# 그룹핑 한 개수
df.groupby('학교').size()
df['학교'].value_counts()

학교
구로고     5
디지털고    3
Name: count, dtype: int64

In [6]:
df['학년'] = [3,3,2,1,1,3,2,2]

In [7]:
df.groupby('학교')['학년'].value_counts()
df.groupby('학교')['학년'].value_counts().loc['구로고']
df.groupby('학교')['학년'].value_counts().loc['디지털고']
# rormalize 백분율로 표시 : 원형 그래프
df.groupby('학교')['학년'].value_counts(normalize=True).loc['구로고']

학년
3    0.4
1    0.4
2    0.2
Name: proportion, dtype: float64

In [8]:
# df.groupby('학년')['키'].mean().sort_values()
df.groupby('학년')[['국어','영어']].sum().sort_values('국어') # 기준추가('국어')
df.groupby('학교')[['국어','영어']].mean().sort_values('영어')
df.groupby('학교')[['국어','영어']].count().sort_values('영어')

      국어  영어
학교
디지털고   3   3
구로고    5   5

In [9]:
df = pd.read_csv('file/drinks.csv')
# continent 대륙별 퍼센트를 출력하시오.
(df['continent'].value_counts(normalize=True)*100)

continent
AF    31.176471
EU    26.470588
AS    25.882353
OC     9.411765
SA     7.058824
Name: proportion, dtype: float64