In [1]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [2]:
# 컬럼전체 이름변경
df['학교'] = df['학교'] +'등학교'
# df.replace({'고':'고등학교'},inplace=True)
# df['학교'] = df['학교'].str.replace({'고':'고등학교'})
# df

In [3]:
# 키 + cm 추가
# df['키'] = df['키'] + 'cm' #df['키']:int, cm:str 타입이 틀려서 에러
# df['키'] = df['키'] + 100 # int+int 가능

# 타입이 다른 경우, 타입변경후 적용
df['키'] = df['키'].astype(str) + 'cm' # str으로 변환

In [4]:
# 함수 적용 : apply() - 컬럼 전체에 적용
def add_cm(h):
    return str(h)+'센티미터'

df['키'] = df['키'].apply(add_cm)

In [5]:
df['SW특기']

지원번호
1번        Python
2번          Java
3번    Javascript
4번           NaN
5번           NaN
6번             C
7번        PYTHON
8번            C#
Name: SW특기, dtype: str

In [6]:
# 함수적용
def capChange(lang):
    if pd.notnull(lang):
        return lang.lower()
    else:
        return "특기없음"
    

df['SW특기'] = df['SW특기'].apply(capChange) # NaN 데이터가 있어서 에러 (조건문을 달아야함)
df['SW특기']

# 이상태로만 출력하면 에러
# df['SW특기'] = df['SW특기'].apply(capChange) # NaN 데이터가 있어서 에러 (조건문을 달아야함)
# df['SW특기']

# df['SW특기'].str.lower()

지원번호
1번        python
2번          java
3번    javascript
4번          특기없음
5번          특기없음
6번             c
7번        python
8번            c#
Name: SW특기, dtype: str

In [7]:
df.columns

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [8]:
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [9]:
# 1.합계 : 과목총점을 계산해서 컬럼을 추가하시오.
# 2.평균 컬럼을 추가하시오.
# 3.등급 컬럼을 추가해서 90점이상 A, 80점이상 B, 70점 C, 60점 D, F 를 입력하시오.
# 함수를 사용할것

df['합계'] = df['국어'] + df['영어'] + df['수학'] + df['과학'] + df['사회']
df['평균'] = df['합계']/5
df['등급'] = 'F'

def cal_rank(s):
    if s>=90: return 'A'
    elif s>=80: return 'B'
    elif s>=70: return 'C'
    elif s>=60: return 'D'
    else: return 'F'

df['등급'] = df['평균'].apply(cal_rank)
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계    평균 등급
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455  91.0  A
2번    강태원   구로고  184   40   35   50  55  25        Java  205  41.0  F
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380  76.0  C
4번    김수찬   구로고  187   40   60   70  75  80         NaN  325  65.0  D
5번    김재욱   구로고  188   15   20   10  35  10         NaN   90  18.0  F
6번    박동현  디지털고  202   80  100   95  85  80           C  440  88.0  B
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  240  48.0  F
8번    승근열  디지털고  190  100   85   90  95  95          C#  465  93.0  A

In [10]:
# 등수 : ascending=False 역순정렬, method='min'1,2,2,4
df['등수'] = df['합계'].rank(ascending=False).astype(int)

In [11]:
df = pd.read_excel('file/students.xlsx',index_col='번호')

In [12]:
df['합계'] = df['국어'] + df['영어'] + df['수학'] 
df['평균'] = df['합계']/3

In [13]:
df.drop(columns={'평균'},inplace=True)

In [14]:
# method='min': 1,2,2,4 / method='dense'1,2,3,4
df['등수'] = df['합계'].rank(ascending=False, method='dense').astype(int)

In [15]:
df.sort_values('합계',ascending=False).head(30)

            이름    학교  학년    키  국어  영어  수학        SW특기   합계  등수
번호
77       Lorna   신림고   1  208  99  98  86      Python  283   1
98       Fiona   신림고   1  200  97  95  84           C  276   2
39         Ban   구로고   1  185  82  94  80      Python  256   3
34      Nollie  디지털고   1  197  84  89  78           C  251   4
62       Sheba  디지털고   1  184  88  90  67           c  245   5
81      Yancey   신림고   3  185  87  92  66      python  245   5
43        Dale   신림고   2  192  91  96  55      PYTHON  242   6
17       Alric   구로고   1  193  68  96  76        JAVA  240   7
52        Buck   신림고   2  187  93  71  75           c  239   8
73       Moise  디지털고   3  185  90  83  65        JAVA  238   9
29     Timoteo   신림고   2  209  77  94  67      Python  238   9
84         Ola  디지털고   3  170  84  77  77  Javascript  238   9
5       Dallis  디지털고   1  209  97  57  76           C  230  10
93       Kiele   구로고   3  193  68  99  62              229  11
100   Jonathan  디지털고   2  195  84  63  80        JAVA  227  12
58     Diahann   구로고   3  184  90  57  78           c  225  13
54         Ula   신림고   3  168  80  59  85        java  224  14
22        Abbe   구로고   1  188  72  65  86           c  223  15
13      Ardene  디지털고   2  161  91  97  33        JAVA  221  16
51   Madeleine  디지털고   1  177  86  55  78              219  17
47      Perkin  디지털고   2  169  82  73  62      python  217  18
65        Kiri   신림고   3  178  64  83  68        JAVA  215  19
32      Hamnet   신림고   3  171  95  55  65  Javascript  215  19
99        Leif   구로고   2  192  96  84  34      PYTHON  214  20
67    Filberto  디지털고   1  196  60  76  78           c  214  20
96        Luke   신림고   3  187  91  63  59      Python  213  21
27      Gordan  디지털고   1  183  90  31  90      PYTHON  211  22
3    Appolonia   구로고   3  193  77  52  81           C  210  23
44    Lisabeth   구로고   3  186  78  79  52           C  209  24
33    Robinson  디지털고   2  181  55  83  70      PYTHON  208  25