In [96]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [97]:
# 컬럼선택 : df[컬럼], 2개이상 []리스트로 추가
df[['이름','키','학교']]
df.columns # 컬럼전체출력
df.columns[0]
df.columns[1]
df.columns[-1]     # 마지막 컬럼명 출력
df['SW특기']        # 마지막 컬럼 출력
df[df.columns[-1]] # 마지막 컬럼 출력
df[['이름','학교']]
df[df.columns[[0,3,-1]]] # 컬럼명을 여러개 사용해서 출력

       이름   국어        SW특기
지원번호
1번    강나래   90      Python
2번    강태원   40        Java
3번    강호림   80  Javascript
4번    김수찬   40         NaN
5번    김재욱   15         NaN
6번    박동현   80           C
7번    박혜정   55      PYTHON
8번    승근열  100          C#

In [98]:
df['이름'] # df[컬럼명만 들어갈수 있음]

# 컬럼 슬라이싱
df[df.columns[[0,3,-1]]] # 컬럼 슬라이싱
df[df.columns[1:4]] # 컬럼 슬라이싱
df.columns[1:4] # 컬럼명

Index(['학교', '키', '국어'], dtype='str')

In [99]:
# rows에 대한 슬라이싱
df[0:3] # rows에 대한 슬라이싱
df['이름'][1:3]
df[['이름','학교','SW특기']][2:]
df['이름'][:3]
# df.iloc[[0,1,2]]

지원번호
1번    강나래
2번    강태원
3번    강호림
Name: 이름, dtype: str

In [100]:
df = pd.read_csv('file/drinks.csv')
df['continent'] # 마지막 컬럼 출력
df[df.columns[-1]] # 마지막 컬럼 출력

0      AS
1      EU
2      AF
3      EU
4      AF
       ..
188    SA
189    AS
190    AS
191    AF
192    AF
Name: continent, Length: 193, dtype: str

In [103]:
# df = pd.read_excel('file/연령별인구현황_2025.xlsx')
# df.columns
df = pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3)
df.columns[[2,3,7,8]]
df[df.columns[[2,3,7,8]]]

         총 인구수     연령구간인구수     30~39세     40~49세
0   51,159,889  51,159,889  6,649,487  7,627,071
1    9,323,492   9,323,492  1,453,915  1,370,576
2    3,251,625   3,251,625    388,293    464,061
3    2,357,040   2,357,040    284,076    338,976
4    3,041,215   3,041,215    427,940    474,175
5    1,398,538   1,398,538    173,489    215,553
6    1,440,682   1,440,682    193,281    210,477
7    1,093,317   1,093,317    136,397    170,157
8      392,154     392,154     58,404     76,817
9   13,715,016  13,715,016  1,915,357  2,191,701
10   1,510,181   1,510,181    158,114    196,699
11   1,591,815   1,591,815    190,906    222,510
12   2,136,299   2,136,299    252,062    315,039
13   1,729,337   1,729,337    172,529    229,830
14   1,782,183   1,782,183    169,648    229,537
15   2,516,753   2,516,753    253,958    337,104
16   3,214,016   3,214,016    343,941    480,612
17     666,226     666,226     77,177    103,247

In [109]:
# 가장많이 사용 꼭 기억할것
df = pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3,usecols='C:D,H:I')
#str타입 replace함수 : 천단위 쉼표 삭제
# 타입변경 : astype(int) - float,str
df[:1]['총 인구수'].str.replace(',','').astype(int)

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

0    51159889
Name: 총 인구수, dtype: int64

In [108]:
df = pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3,index_col='행정기관')
df.columns

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Index(['행정기관코드', '총 인구수', '연령구간인구수', '0~9세', '10~19세', '20~29세', '30~39세',
       '40~49세', '50~59세', '60~69세',
       ...
       '10~19세.17', '20~29세.17', '30~39세.17', '40~49세.17', '50~59세.17',
       '60~69세.17', '70~79세.17', '80~89세.17', '90~99세.17', '100세 이상.17'],
      dtype='str', length=235)